// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID            int64
	Slug          string
	Name          string
	PriceAmount   int64
	PriceCurrency string
	CreatedAt     pgtype.Timestamptz
}
