// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"
)

const insertProductIfMissing = `-- name: InsertProductIfMissing :exec
INSERT INTO products (slug, name, price_amount, price_currency)
SELECT $1::text, $2::text, $3::bigint, $4::char(3)
WHERE NOT EXISTS (SELECT 1 FROM products WHERE slug = $1::text)
ON CONFLICT (slug) DO NOTHING
`

type InsertProductIfMissingParams struct {
	Slug          string
	Name          string
	PriceAmount   int64
	PriceCurrency string
}

// Inserts a product only when its slug is new. INSERT … SELECT draws an id only for a row it actually
// inserts, unlike ON CONFLICT, which uses one up on every attempt.
func (q *Queries) InsertProductIfMissing(ctx context.Context, arg InsertProductIfMissingParams) error {
	_, err := q.db.Exec(ctx, insertProductIfMissing,
		arg.Slug,
		arg.Name,
		arg.PriceAmount,
		arg.PriceCurrency,
	)
	return err
}

const listProducts = `-- name: ListProducts :many
SELECT id, slug, name, price_amount, price_currency
FROM products
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListProductsParams struct {
	AfterID  int64
	RowLimit int32
}

type ListProductsRow struct {
	ID            int64
	Slug          string
	Name          string
	PriceAmount   int64
	PriceCurrency string
}

// One page in id order, after the cursor's id. The caller asks for one row more than the page size to
// learn whether another page follows.
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.AfterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.PriceAmount,
			&i.PriceCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :execrows
UPDATE products
SET name = $1, price_amount = $2, price_currency = $3
WHERE slug = $4
  AND (name, price_amount, price_currency)
      IS DISTINCT FROM ($1::text, $2::bigint, $3::char(3))
`

type UpdateProductParams struct {
	Name          string
	PriceAmount   int64
	PriceCurrency string
	Slug          string
}

// Updates a product by slug only when something changed, so reseeding writes nothing.
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProduct,
		arg.Name,
		arg.PriceAmount,
		arg.PriceCurrency,
		arg.Slug,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
