// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"
)

const listProducts = `-- name: ListProducts :many
SELECT id, slug, name, price_amount, price_currency
FROM products
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListProductsParams struct {
	AfterID  int64
	RowLimit int32
}

type ListProductsRow struct {
	ID            int64
	Slug          string
	Name          string
	PriceAmount   int64
	PriceCurrency string
}

// One page in id order, after the cursor's id. The caller asks for one row more than the page size to
// learn whether another page follows.
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.AfterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.PriceAmount,
			&i.PriceCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProduct = `-- name: UpsertProduct :exec
INSERT INTO products (slug, name, price_amount, price_currency)
VALUES ($1, $2, $3, $4)
ON CONFLICT (slug) DO UPDATE
SET name = EXCLUDED.name, price_amount = EXCLUDED.price_amount, price_currency = EXCLUDED.price_currency
WHERE (products.name, products.price_amount, products.price_currency)
    IS DISTINCT FROM (EXCLUDED.name, EXCLUDED.price_amount, EXCLUDED.price_currency)
`

type UpsertProductParams struct {
	Slug          string
	Name          string
	PriceAmount   int64
	PriceCurrency string
}

// Inserts a product, or updates it by slug only when something changed, so reseeding is a no-op.
func (q *Queries) UpsertProduct(ctx context.Context, arg UpsertProductParams) error {
	_, err := q.db.Exec(ctx, upsertProduct,
		arg.Slug,
		arg.Name,
		arg.PriceAmount,
		arg.PriceCurrency,
	)
	return err
}
